#!/usr/bin/env python3
"""T70 final repository audit - publication readiness."""
import os
import sys
import subprocess
from pathlib import Path

sys.stdout.reconfigure(encoding='utf-8')
REPO = Path(r'D:\新论文\实验')

print("=" * 70)
print("REPOSITORY PUBLICATION READINESS AUDIT")
print("=" * 70)

# 1. Top-level structure
print("\n--- 1. Top-level structure ---")
for item in sorted(REPO.iterdir()):
    if item.is_dir() and not item.name.startswith('__') and not item.name.startswith('_'):
        n = sum(1 for _ in item.rglob('*') if _.is_file())
        print(f"  {item.name + '/':30s} {n:>6} files")
    elif item.is_file() and not item.name.startswith('__') and not item.name.startswith('_') \
            and not item.name.endswith('.bak') and not item.name.endswith('.ps1.disabled') \
            and not item.name.endswith('.log.disabled') and not item.name.endswith('.err.log') \
            and not item.name.endswith('.log') and not item.name.endswith('.err') \
            and item.name not in ('论文', 'watchdog.ps1.disabled'):
        size_kb = item.stat().st_size / 1024
        print(f"  {item.name:30s} {size_kb:>8.1f} KB")

# 2. Critical files
print("\n--- 2. Critical files ---")
critical = ['LICENSE', 'README.md', 'requirements.txt', 'CITATION.cff',
            '.gitignore', 'run_all.sh']
for f in critical:
    p = REPO / f
    if p.exists():
        print(f"  ✓ {f}: {p.stat().st_size:,} bytes")
    else:
        print(f"  ✗ MISSING: {f}")

# 3. Data integrity
print("\n--- 3. Data integrity (paper claims) ---")
import json
checks = []
for f, expect_algos, expect_probs, expect_seeds, expect_total in [
    ('sec_main_v3.json', 6, 14, 30, 2520),
    ('exp6_cross_llm_n14.json', 3, 14, 30, 1260),
    ('exp7_ablation_combined.json', 4, 14, 30, 1680),
]:
    p = REPO / 'results' / 'raw' / f
    if p.exists():
        with open(p, 'r', encoding='utf-8') as fh:
            d = json.load(fh)
        n = len(d)
        # Get unique
        a_field = 'algo' if 'algo' in d[0] else ('model' if 'model' in d[0] else 'version')
        p_field = 'problem' if 'problem' in d[0] else 'prob'
        algos = set(r.get(a_field) for r in d)
        probs = set(r.get(p_field) for r in d)
        seeds = set(r.get('seed') for r in d)
        match = (n == expect_total and
                 len(algos) == expect_algos and
                 len(probs) == expect_probs and
                 len(seeds) == expect_seeds)
        sym = '✓' if match else '✗'
        print(f"  {sym} {f}: {n} records ({len(algos)} algos, {len(probs)} probs, {len(seeds)} seeds) - expect {expect_total}/{expect_algos}/{expect_probs}/{expect_seeds}")
    else:
        print(f"  ✗ MISSING: {f}")

# 4. LLM cache
print("\n--- 4. LLM cache (for reproducibility) ---")
cache = list((REPO / 'results' / 'llm_cache').rglob('*'))
n_cache = sum(1 for f in cache if f.is_file())
total_size = sum(f.stat().st_size for f in cache if f.is_file())
print(f"  Files: {n_cache}")
print(f"  Total: {total_size / 1024 / 1024:.2f} MB")
print(f"  Commit policy: COMMITTED (per .gitignore fix)")

# 5. Figures
print("\n--- 5. Figures ---")
figs = list((REPO / 'results' / 'figures').rglob('*.png')) + list((REPO / 'results' / 'figures').rglob('*.pdf'))
print(f"  Total: {len(figs)} figures")
print(f"  Commit policy: NOT committed (regenerated by plot scripts)")

# 6. Smoke test summary
print("\n--- 6. Smoke test (verified earlier) ---")
print("  ✓ All 5 core packages import cleanly")
print("  ✓ End-to-end TLE run on DF1 produces valid output JSON")
print("  ✓ IGD = 0.0895 in 2.0s with cache (cache-hit fast path works)")

# 7. Key user-facing entry points
print("\n--- 7. Entry points for users ---")
print("  bash run_all.sh                  # full reproduction (1.5-2h with cache)")
print("  bash run_all.sh --quick          # 2-seed smoke test (~5 min)")
print("  bash run_all.sh --clean          # ignore cache (22-24h fresh)")
print("  python -m proposed.run_tle --help # single-problem CLI")
print("  python -m _smoke_test.py         # 5-step import/render check")
print("  python -c 'import core.tle'      # verify install")

# 8. Stats
print("\n--- 8. Final stats ---")
total_size = sum(f.stat().st_size for f in REPO.rglob('*') if f.is_file())
size_mb = total_size / 1024 / 1024
n_files = sum(1 for f in REPO.rglob('*') if f.is_file())
print(f"  Total files: {n_files}")
print(f"  Total size:  {size_mb:.1f} MB")
print(f"  Of which LLM cache: {total_size/1024/1024 - (size_mb - total_size/1024/1024):.1f} MB")
print(f"  GitHub URL in paper: github.com/Ss1mpleee/A-Triggered-LLM-Enhanced-Framework-for-Dynamic-Multi-Objective-Optimization-An-Empirical-Study")
